### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by giovinko** [Chemsse57/TwitterFollowerScraper#1]
Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\ADMIN\documents\tn\scraper.py", line 143, in <module>
    data = scrape_users(args.option)
  File "C:\Users\ADMIN\documents\tn\scraper.py", line 52, in scrape_users
    user_count = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.XPATH, f'//*[@id="profile-stat-{option}-value"]')))
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00E55523+24195]
        (No symbol) [0x00DEAA04]
        (No symbol) [0x00CE2093]
        (No symbol) [0x00D26ED2]
        (No symbol) [0x00D2711B]
        (No symbol) [0x00D676F2]
        (No symbol) [0x00D4AB84]
        (No symbol) [0x00D65280]
        (No symbol) [0x00D4A8D6]
        (No symbol) [0x00D1BA27]
        (No symbol) [0x00D1C43D]
        GetHandleVerifier [0x0111CE13+2938739]
        GetHandleVerifier [0x0116EC69+3274185]
        GetHandleVerifier [0x00EE09C2+594722]
        GetHandleVerifier [0x00EE7EDC+624700]
        (No symbol) [0x00DF37CD]
        (No symbol) [0x00DF0528]
        (No symbol) [0x00DF06C5]
        (No symbol) [0x00DE2CA6]
        BaseThreadInitThunk [0x76B07BA9+25]
        RtlInitializeExceptionChain [0x776BC0CB+107]
        RtlClearBits [0x776BC04F+191]

**Comment by ntegrals** [comment]
@giovinko I'm facing the same issue.

Any idea how to resolve this? @Chemsse57 

I've also tried upgrading to the "Old Twitter Layout 2024" extension, but it doesn't support unsigned requests. (And I'm not sure how sign them)

**Comment by Chemsse57** [comment]
it's because removed the oldTwitter extension because does'nt work anymore. 
With the new version, you won't need it anymore and it should work again.

**Comment by ntegrals** [comment]
@Chemsse57 Awesome. Thanks a lot!

**Comment by giovinko** [comment]
> it's because removed the oldTwitter extension because does'nt work anymore. With the new version, you won't need it anymore and it should work again.

Okay man, thank you

**Comment by giovinko** [comment]
> it's because removed the oldTwitter extension because does'nt work anymore. With the new version, you won't need it anymore and it should work again.
@Chemsse57 

Still getting errors man, anyway I can reach out to you for guidance. Please 🙏
